apiVersion: v1
kind: Pod
metadata:
  name: sharoncohen1
  labels:
    app: sharoncohen1
spec:
  containers:
    - name: sharoncohen1
      image: sharonkohen/sharoncohen:latest-00
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sharoncohen1
spec:
  type: LoadBalancer
  selector:
    app: sharoncohen1
  ports:
    - name: http
      port: 80
      targetPort: 3000
